name: shelf_films_demo02
description: A simple command-line application.
environment: 
  sdk: '>=2.12.1 <3.0.0'
dependencies: 
  shelf_router: ^1.1.1
  dart_ipify: ^1.1.1
  shelf_cors_headers: ^0.1.2
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.3.2
  envify: ^2.0.2
  redis: ^2.0.0
  uuid: ^3.0.4
  sqlite3: ^1.1.2
  path:
  ffi:


dev_dependencies:
  pedantic: ^1.11.1
